# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# compile CXX with /Library/Developer/CommandLineTools/usr/bin/c++
CXX_DEFINES = 

CXX_INCLUDES = -isystem /usr/local/Cellar/opencv/4.8.1_5/include/opencv4

CXX_FLAGS = -std=gnu++11 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.2.sdk -mmacosx-version-min=13.5

